name: Roll release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check Repo...
      uses: actions/checkout@v5

    - name: Build distributable binary...
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        python setup.py build
        zip -r simple.zip build/*
 
    - name: Release...
      uses: softprops/action-gh-release@v2
      with:
        tag_name: roll
        body_path: README.md
        files: simple.zip
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
